name: repro_examples
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3
  - dask
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - seaborn
  - xarray
  - zarr
  - pip:
    - pytrends
