#!/bin/bash

# get HadISST data
mkdir -p input_data
curl \
  -o "input_data/HadISST_sst.nc.gz" \
  "https://www.metoffice.gov.uk/hadobs/hadisst/data/HadISST_sst.nc.gz"
gunzip input_data/HadISST_sst.nc.gz
